name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Construye tu app React
      - name: Install & Build (React)
        working-directory: ./test/contacts-app
        run: |
          npm ci
          npm run build

      # Sube a Azure Static Web Apps usando el token de despliegue
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # <-- crea este secret con el Deployment Token de TU SWA
          action: "upload"
          app_location: "./test/contacts-app"
          # IMPORTANTE: elige UNA de las dos siguientes líneas según tu builder:
          # output_location: "build"     # React CRA
          output_location: "dist"        # Vite (comenta la otra)
          skip_app_build: true           # ya construimos arriba

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v2
        with:
          action: "close"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
