name: Build and deploy ASP.Net Core app to Azure Web App - mcacontacts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore solution
        run: dotnet restore "./test/ContactApi/ContactApi.sln"

      - name: Build solution (Release)
        run: dotnet build "./test/ContactApi/ContactApi.sln" --configuration Release --no-restore

      # Publica SOLO el proyecto WebAPI
      - name: Publish WebAPI project
        run: dotnet publish "./test/ContactApi/ContactApi.Api/ContactApi.Api.csproj" -c Release -o "${{ env.DOTNET_ROOT }}/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2A4DB492991495E83CB1EE83A58B657 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A5A3C7B7ED7E4D848630E5EDE98922C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D1C4F0FEA19E4188A7FDDE0B75E2337E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mcacontacts'
          slot-name: 'Production'
          package: .
